<?php
require '.:/usr/share/php/libphp-phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer;
$mail->setFrom('rekodevtest@gmail.com');
$mail->addAddress('macgeekfromapple@gmail.com');
$mail->Subject = 'Message sent by PHPMailer';
$mail->Body = '<h2>Hello!</h2><p style="color:Blue;">
I am using PHPMailer to send email</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'ssl://smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = 'rekodevtest@gmail.com';
$mail->Password = 'Rekodevgruppe69!';
if(!$mail->send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  echo 'Email has been sent.';
}
?>